name: ramp-variable-stars
channels:
  - defaults
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=0.22
  - PyWavelets
  - pip
  - pip:
    - ramp-workflow

# To activate the ramp-variable-stars environment
# conda activate ramp-variable-stars

# Update environement with environment.yml
# conda env update --file environment.yml --prune